name: Validate JSONs

on:
  push:
    branches: [main]
  pull_request:

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Validate JSON with Glob
        uses: nhalstead/validate-json-action@v0.1.10
        with:
          jsons: constants/**/*.json
